#mongodb
spring:
  data:
    mongodb:
      authentication-database: admin
      username: myUserAdmin
      password: root
      host: localhost
      port: 27017
      database: test_db
  mail:
    username: xxxxxx@gmail.com
    password: xxxxxx
    host: localhost
